
package siscdm.registro;

import siscdm.ficha.ingreso.egreso.Ficha_Ingreso_Egreso;
import siscdm.registro.paciente.Identificacion;

/**
 *
 * @author Data Collectors
 */
public class Ventana_registro extends javax.swing.JFrame {

    /**
     * Creates new form Ventana_registro
     */
    public Ventana_registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        botonPrueba = new javax.swing.JButton();
        botoncorre = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonPrueba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siscdm/registro/img/nuevo.png"))); // NOI18N
        botonPrueba.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        botonPrueba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonPrueba.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        botonPrueba.setIconTextGap(10);
        botonPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPruebaActionPerformed(evt);
            }
        });
        desktopPane.add(botonPrueba);
        botonPrueba.setBounds(260, 150, 110, 100);

        botoncorre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siscdm/registro/img/traslado.png"))); // NOI18N
        botoncorre.setText("jButton1");
        botoncorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoncorreActionPerformed(evt);
            }
        });
        desktopPane.add(botoncorre);
        botoncorre.setBounds(500, 150, 130, 100);
        desktopPane.add(jLabel1);
        jLabel1.setBounds(0, 0, 50, 30);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 875, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPruebaActionPerformed
        // TODO add your handling code here:
        Identificacion IdReg = new Identificacion();
        desktopPane.add(IdReg);
        IdReg.setVisible(true);
    }//GEN-LAST:event_botonPruebaActionPerformed

    private void botoncorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoncorreActionPerformed
        // TODO add your handling code here:
        Ficha_Ingreso_Egreso IdReg = new Ficha_Ingreso_Egreso();
        desktopPane.add(IdReg);
        IdReg.setVisible(true);
    }//GEN-LAST:event_botoncorreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana_registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonPrueba;
    private javax.swing.JButton botoncorre;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
